name: flutter_audio_desktop
description: A simple audio playback library for Flutter Desktop. Supports MP3, FLAC & WAV on Windows & Linux.
version: 0.0.8
homepage: https://github.com/alexmercerind/flutter_audio_desktop
repository: https://github.com/alexmercerind/flutter_audio_desktop
documentation: https://github.com/alexmercerind/flutter_audio_desktop/blob/master/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterAudioDesktopPlugin
      windows:
        pluginClass: FlutterAudioDesktopPlugin